### PR TITLE
WIP : include/exclude IfdPathAndTag w/AddTagsFromExistingWithFilter

### PR DESCRIPTION
**Pull request by scottleedavis**
https://github.com/dsoprea/go-exif/issues/16
https://github.com/mattermost/mattermost-server/issues/10336

Please let me know what I can improve.

### CODE REVIEW

**Comment by dsoprea** [comment]
I haven't taken a close look at this, yet, but the first two commits can be discarded. We already calculate the GPS degree components as _float64_ and we won't accept merge commits.

**Comment by scottleedavis** [comment]
I had merged master to my fork of your  branch, so that is why those commits are there.  If you merge master to your branch the commits will disappear as they will already be there.  Otherwise if you want me to remove them I will.  :)

**Comment by dsoprea** [comment]
It's your contribution. Please clean it up yourself.

**Comment by scottleedavis** [comment]
You got it!  Done.

**Comment by scottleedavis** [comment]
Hello!  Are there any things I can fix, improve upon or add?

**Comment by scottleedavis** [comment]
going to move forward with a wrapper module https://github.com/scottleedavis/go-exif-remove

**Pull request closed without merging**
