### PR TITLE
Collect goes into an infinite loop for a broken jpg file

### PR DESCRIPTION
**Pull request by vansante**
As the title notes, I have a file that causes go-exif to go into a (seemingly) infinite loop and causes my program and the testcase to crash.

I've created a testcase with the file attached in this MR. I don't know how to fix the actual problem though, so I hope you can figure that part out! :)

### CODE REVIEW

**Comment by vansante** [comment]
@dsoprea After setting some breakpoints I found a possible fix for the infinite loop, see 02f2923

**Comment by dsoprea** [comment]
Thanks for trying the PR. I'll take a look as soon as I can.

**Comment by vansante** [comment]
@dsoprea Did you have time to take a look?

**Comment by dsoprea** [comment]
Not yet, sorry. I'll try to take a look today.

**Comment by dsoprea** [comment]
The problem with this is that all offsets in the EXIF structure are absolute offsets to anywhere in the blob. This PR would be a bug in itself.

You haven't provided any output or actual details of this looping behavior. Depending on why it's looping, there could be an alternative, very-easy fix (e.g. looping because we're parsing through random binary garbage versus looping over the same IFDs repeatedly).

**Comment by vansante** [comment]
@dsoprea That is why I attached the faulting image, its relatively easy to run the test case with an attached debugger and see it go to the same offset over and over again? I'm not sure how I can make that more clearer?

**Comment by dsoprea** [comment]
Please share the URL to the comment where you supposedly "attached" it.

**Comment by vansante** [comment]
@dsoprea I apologise, I am not trying to be rude, I was merely asking a question.

As to where the image was, it's in the actual merge request we are commenting on, see [here](https://github.com/vansante/go-exif/blob/02f29239d22ee09d7ca09b17a2dd087b28e211be/v3/assets/broken_exif.jpg).

In the same commit, I added the unit test I was referring to earlier, you can launch with a debugger and see it getting stuck on the same offset over and over again. You can find that [here](https://github.com/vansante/go-exif/blob/02f29239d22ee09d7ca09b17a2dd087b28e211be/v3/exif_test.go).

I hope that clears everything up!

**Pull request closed without merging**
